import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateScheduleTruckDto } from './dto/create-schedule-truck.dto';
import { UpdateScheduleTruckDto } from './dto/update-schedule-truck.dto';
import { firstValueFrom } from 'rxjs';
import { format } from 'date-fns';
import { HttpService } from '@nestjs/axios';

@Injectable()
export class ScheduleTruckService {
  constructor(
    private prisma: PrismaService,
    private http: HttpService,
  ) {}

  async create(dto: CreateScheduleTruckDto) {
    const schedule = await this.prisma.scheduleTruck.create({
      data: {
        truckId: dto.truckId,
        driverId: dto.driverId,
        scheduleAt: new Date(dto.scheduleAt),
        cycle: dto.cycle ? Number(dto.cycle) : undefined,
        customers: {
          create: (dto.customerIds ?? []).map((id) => ({ customerId: id })),
        },
      },
      include: {
        truck: true,
        driver: true,
        customers: { include: { customer: true } },
        deliveryOrders: true,
      },
    });
    // Format tanggal schedule
    const tanggal = format(schedule.scheduleAt, 'dd-MM-yyyy');
    // Hitung panjang label paling panjang secara otomatis
    const labels = ['DATE', 'TRUCK', 'DRIVER', 'CYCLE', 'CUSTOMER'];
    const maxLabelLength = Math.max(...labels.map((l) => l.length));

    // Fungsi pad label + 2 spasi sebelum ":"
    const padLabel = (label: string) => label.padEnd(maxLabelLength + 2, ' ');

    const pesan = `*NEW DELIVERY SCHEDULE*
───────────────
\`\`\`
${padLabel('DATE')}: ${tanggal}
${padLabel('TRUCK')}: ${schedule.truck?.noPol ?? '-'}
${padLabel('DRIVER')}: ${schedule.driver?.name ?? '-'}
${padLabel('CYCLE')}: ${schedule.cycle ?? '-'}
${padLabel('CUSTOMER')}: ${schedule.customers.map((c) => c.customer.name).join(', ') || '-'}
\`\`\`
───────────────
> _Generated by NOVA_ `;

    // Kirim ke WA group

    return schedule;
  }

  findAll() {
    return this.prisma.scheduleTruck.findMany({
      include: {
        truck: true,
        driver: true,
        customers: { include: { customer: true } },
        deliveryOrders: true,
      },
    });
  }

  findOne(id: number) {
    return this.prisma.scheduleTruck.findUnique({
      where: { id },
      include: {
        truck: true,
        driver: true,
        customers: { include: { customer: true } },
        deliveryOrders: true,
      },
    });
  }

  update(id: number, dto: UpdateScheduleTruckDto) {
    if (!dto.scheduleAt) {
      throw new Error('scheduleAt is required');
    }

    return this.prisma.scheduleTruck.update({
      where: { id },
      data: {
        truckId: dto.truckId,
        driverId: dto.driverId,
        scheduleAt: new Date(dto.scheduleAt), // sekarang pasti string
        customers: {
          deleteMany: {},
          create: (dto.customerIds ?? []).map((id) => ({ customerId: id })),
        },
      },
      include: {
        truck: true,
        driver: true,
        customers: { include: { customer: true } },
        deliveryOrders: true,
      },
    });
  }

  remove(id: number) {
    return this.prisma.$transaction(async (prisma) => {
      // Hapus dulu semua relasi customer
      await prisma.scheduleCustomer.deleteMany({
        where: { scheduleTruckId: id },
      });

      // Hapus dulu semua delivery orders terkait
      await prisma.deliveryOrder.deleteMany({
        where: { scheduleId: id },
      });

      // Baru hapus scheduleTruck
      return prisma.scheduleTruck.delete({
        where: { id },
      });
    });
  }
}
